site_name: Very cool Anarchy server
site_url: https://man.servegame.com/ManTech-Wiki

theme:
  name: material
  logo: logo.png
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.indexes

plugins:
  - search

extra_javascript:
  - script.js

nav:
  - General: index.md
  - Rewards: rewards/index.md
  - FAQ: faq/index.md
  - Resource Packs: resource-packs/index.md
  - Support: support/index.md

markdown_extensions:
  - attr_list  # For button styling
  - admonition
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg