authors:
  auzer:
    name: Auzer1
    description: Server Admin
    avatar: https://avatars.githubusercontent.com/u/583231?v=4
  funod:
    name: FunOD
    description: Server Admin
    avatar: https://avatars.githubusercontent.com/u/583231?v=4
